/**
 * @getmarrow/sdk - Runtime control, proof, and fleet intelligence for AI agents
 *
 * @packageDocumentation
 */

import { MarrowClient } from './client';

export { MarrowClient, MarrowLoopRequiredError, classifyMarrowFailure } from './client';
export { createMarrowClient, marrowFromEnv } from './factory';
export { resolveMarrowEnv } from './env';
export type { MarrowResolvedEnv, MarrowResolveEnvOptions } from './env';

export type {
  // Core Types
  MarrowDecisionType,
  MarrowEnforcementMode,
  MarrowDecisionSourceKind,
  MarrowDecisionSourceChannel,
  MarrowDecisionSourceClient,
  MarrowDecisionUserIntent,
  MarrowDecisionSourceMeta,
  MarrowDecisionProvenanceInput,
  Narrative,
  MarrowLoopRecommendation,
  MarrowBlockReasonCode,
  MarrowActionClass,
  MarrowChokePoint,

  // Memory Types
  MemoryStatus,
  MemoryAuditAction,
  MarrowMemory,
  MarrowMemoryAuditEntry,
  MarrowMemoryRetrievalResult,
  MemoryShareOptions,
  MemoryExportOptions,
  MemoryImportOptions,
  MemoryRetrieveOptions,
  ApiKeyType,
  ApiKeyScope,
  CreateApiKeyParams,
  MarrowApiKey,
  CreateApiKeyResult,
  ListApiKeysResult,
  RevokeApiKeyResult,
  RotateApiKeyResult,
  ApiKeyAuditEntry,
  GetKeyAuditParams,
  GetKeyAuditResult,

  // Loop Types
  MarrowLoopState,
  MarrowCheckResult,
  MarrowEnforceOptions,
  MarrowActionMeta,
  MarrowAutoWrapOptions,
  MarrowPassiveRuntimeSurface,
  MarrowPassiveRuntimeOptions,
  MarrowPassiveActionOptions,
  MarrowPassiveRuntime,
  MarrowPassiveRuntimeWithLifecycle,
  MarrowFailureType,
  MarrowGuardedRiskPolicy,
  MarrowGuardedRunOptions,
  MarrowGuardedRunResult,
  MarrowActionPermitIssueInput,
  MarrowActionPermitPublic,
  MarrowActionPermitIssueResult,
  MarrowActionPermitVerifyInput,
  MarrowActionPermitVerifyResult,
  MarrowActionPermitCloseInput,
  MarrowActionPermitCloseResult,
  MarrowEnforcementHeartbeatInput,
  MarrowEnforcementCoverageResult,
  MarrowLifecycleEventType,
  MarrowLifecycleEventInput,
  MarrowLifecycleEventResult,
  MarrowLifecycleBacklog,
  MarrowActivationCoverage,
  MarrowIntegrationCapabilityLevel,
  MarrowInterventionDisposition,
  MarrowDecisionTraceResult,
  MarrowInterventionReceipt,

  // Result Types
  MarrowOrientResult,
  MarrowThinkResult,
  MarrowCommitResult,
  MarrowModelUsageInput,
  MarrowModelUsageResult,
  MarrowTokenValueSignal,
  MarrowAskResult,
  MarrowClientUpdateAdvisory,
  MarrowQuickStatusResult,
  ActionableInsight,
  MarrowDashboardResult,
  MarrowDigestResult,
  MarrowAgentStatusState,
  MarrowAgentStatusResult,
  MarrowValueReportResult,
  MarrowDecisionBriefRole,
  MarrowDecisionBriefRiskLevel,
  MarrowDecisionBriefRequest,
  MarrowDecisionBriefResult,
  MarrowArbitrationRiskLevel,
  MarrowArbitrationResolution,
  MarrowArbitrationEvidence,
  MarrowArbitrationProposal,
  MarrowArbitrationRequest,
  MarrowArbitrationProposalScore,
  MarrowArbitrationReceipt,
  MarrowGovernanceMode,
  MarrowGovernanceProject,
  MarrowGovernanceWorkflow,
  MarrowGovernanceAgent,
  MarrowModeRecommendationRequest,
  MarrowModeRecommendationResult,
  MarrowPolicyRule,
  MarrowPolicyProfile,
  MarrowPolicyProfilesResult,
  MarrowCreatePolicyProfileRequest,
  MarrowPolicyProfileResult,
  MarrowAssignProjectPolicyProfileRequest,
  MarrowProjectPolicyProfileAssignment,
  MarrowProjectPolicyProfileAssignmentResult,
  MarrowPolicyResolveRequest,
  MarrowPolicyResolveResult,
  MarrowFleetLessonType,
  MarrowFleetVisibility,
  MarrowHandoffStatus,
  MarrowDeploymentMemoryStatus,
  MarrowMemoryPermission,
  MarrowFleetLesson,
  MarrowFleetLessonsResult,
  MarrowRecordFleetLessonInput,
  MarrowDeploymentMemory,
  MarrowDeploymentMemoryInput,
  MarrowAgentHandoff,
  MarrowCreateHandoffInput,
  MarrowUpdateHandoffInput,
  MarrowMemoryPermissionRecord,
  MarrowSetMemoryPermissionInput,
  MarrowAgentPerformanceResult,
  ImprovementMetricDelta,
  ImprovementActive,
  ImprovementOnboarding,
  Improvement,
  MarrowSessionEndResult,
  MarrowTemplateSummary,
  MarrowTemplateDetail,

  // Config Types
  MarrowClientOptions,
} from './types';

export default MarrowClient;
